name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Project - Desktop
        run: bash ./gradlew desktop:dist
      - name: Build Project - Android
        run: bash ./gradlew android:assembleRelease
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset - Desktop
        id: upload_release_asset_desktop
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: desktop/build/libs/desktop-1.0.jar
          asset_name: multiframe.jar
          asset_content_type: application/java-archive
      - name: Upload Release Asset - Android
        id: upload_release_asset_android
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/build/outputs/apk/release/android-release-unsigned.apk
          asset_name: multiframe.apk
          asset_content_type: application/vnd.android.package-archive
